title: Daniel Sanchez
description: Senior Software Engineer
baseurl: ""
url: https://dfsavi.dev

# site settings
taglong: Senior Software Engineer
tagshort: Sr Software Engineer

# author settings
author:
  name: Daniel Sanchez
  email:
photo: assets/files/photo.jpg
address:
phone:

# social media links
social:
  mastodon: dfsavi
  github: dfsavi
  linkedin: dfsavi

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
  - demo/
  - cvless.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
